### ISSUE TITLE
Icon not showing up

### ISSUE THREAD

**Issue by TEJLJR** [Minh-Ton/VolumeIcon#2]
I don't know what icon its supposed to put, but I cleared my custom for my SSD like the instructions said to, and the icon didn't change at all.

**Comment by minh-ton** [comment]
It will put an icon base on your macOS Version (for example you're on 10.14 then it will put a Mojave icon onto your disk). And it is visible in the boot manager (Holding Option immediately after turning on the computer).

If you want to check if it was being applied successfully or not without reboot your Mac, type this into the Terminal window: ```if [[ -f /Volumes/"YourSelectedVolumeName"/.VolumeIcon.icns ]]; then echo "It existed"; fi```.

**Comment by TEJLJR** [comment]
I’m on 10.14.6 with the dosdude1 patcher

**Comment by minh-ton** [comment]
So it should put a Mojave icon on to your disk.

**Comment by TEJLJR** [comment]
It says event not found, am I typing the terminal command in wrong?

**Comment by minh-ton** [comment]
> It says event not found, am I typing the terminal command in wrong?

Try copy and paste that again (It's still OK for me). Remember to replace the "YourSelectedVolumeName" into your desired one with quotation mark (For example /Volumes/"Macintosh HD").

**Comment by TEJLJR** [comment]
![Screen Shot 2020-05-06 at 12 24 15](https://user-images.githubusercontent.com/18595589/81202373-822adb80-8f94-11ea-8132-e996d865050f.png)

**Comment by minh-ton** [comment]
You should type the command into the Terminal window without the dot at the end

**Comment by TEJLJR** [comment]
Didn’t work. I rebooted, still nothing

**Comment by minh-ton** [comment]
What's the Terminal command output?

**Comment by minh-ton** [comment]
If your volume is not bootable then it won't show up in Boot Manager.

**Comment by TEJLJR** [comment]
> What's the Terminal command output?

Nothing, blank

**Comment by TEJLJR** [comment]
> If your volume is not bootable then it won't show up in Boot Manager. 

It is bootable

**Comment by Minh-Ton** [comment]
If your volume doesn't contain a copy of macOS so nothing will happen. In this case: your selected volume may not contain a copy of macOS so it won't apply an icon to it.

**Comment by TEJLJR** [comment]
But that’s not supposed to be, I have 2 volumes with macOS on it, how can that be? Both are bootable

**Comment by minh-ton** [comment]
OK, so I will show you an alternative way to do it instead.

1. Open VolumeIcon.app (Leave in open until the process finished)
2. Open Terminal and type: ``` sudo cp -a /tmp/volumeicon.bundle/Mojave.icns /Volumes/"YourSelectedVolumeWithQuotation"/.VolumeIcon.icns && rm -R /tmp/volumeicon.bundle ```
3. Close the VolumeIcon app.

**Comment by TEJLJR** [comment]
No such file or directory
![Screen Shot 2020-05-06 at 12 56 31](https://user-images.githubusercontent.com/18595589/81205658-02ebd680-8f99-11ea-817d-0e294c1b5e92.png)

**Comment by minh-ton** [comment]
Have you opened VolumeIcon.app while executing the command?

**Comment by TEJLJR** [comment]
I did, ran the operation, then ran the command in Terminal

**Comment by minh-ton** [comment]
Download Mojave Icon here

https://github.com/Minh-Ton/VolumeIcon/raw/resources/Boot_icons/Mojave.icns

then run sudo cp -a /path_to_downloaded_icon /Volumes/“SelectedVolume”/.VolumeIcon.icns

**Comment by TEJLJR** [comment]
Ok, it worked finally. Thanks

**Comment by TEJLJR** [comment]
Does this command work with other icons as well?

**Comment by TEJLJR** [comment]
I set a custom icon in the Startup Manager, but it doesn't change for the Finder, is there a way to fix this?

![IMG_2712](https://user-images.githubusercontent.com/18595589/81218921-fa050000-8fac-11ea-8cbc-5f088570a755.jpeg)
![Screen Shot 2020-05-06 at 15 20 02](https://user-images.githubusercontent.com/18595589/81218981-1143ed80-8fad-11ea-81e9-0dc6c485e36c.png)
![Screen Shot 2020-05-06 at 15 20 22](https://user-images.githubusercontent.com/18595589/81219009-1c971900-8fad-11ea-8356-4674665f3267.png)

**Comment by minh-ton** [comment]
@TEJLJR Actually, my application is only designed for older Macs that don't support booting off APFS Volume natively. On newer Macs, if you use any icns file and name them as ```.VolumeIcon.icns``` and put this in your boot disk, it would show the icon in the Boot Manager. However, on older Macs, the firmware only recognizes the icon unless we modify the icon's metadata. So what you've downloaded is a modified icon for use on older Macs.

If you want to create your own icon, download Image2Icon from the App Store, and just drag and drop a jpeg or png image file into the app and it will automatically generate an icns file for you. Then you can use the command ```sudo cp -a /path_to_downloaded_icon /Volumes/“SelectedVolume”/.VolumeIcon.icns``` to apply the icon for your disk. Note that this won't change the icon that you see in Finder, but it only changes the icon in Boot Manager.
